# Generated by Django 4.2.1 on 2026-01-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_classgroup_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_tests', to='core.classgroup'),
        ),
        migrations.AddField(
            model_name='test',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_tests', to='core.student'),
        ),
        migrations.AddField(
            model_name='test',
            name='excluded_students',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_tests', to='core.student'),
        ),
    ]
