# Generated by Django 4.2.1 on 2026-01-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_user_alter_student_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='descriptive_structure',
            field=models.TextField(blank=True, help_text='JSON structure for descriptive/hierarchical questions', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('standard', 'Standard Question Bank'), ('descriptive', 'Descriptive/Hierarchical')], default='standard', max_length=20),
        ),
    ]
