# Generated by Django 4.2.1 on 2026-01-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_processedpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('text_line', 'Text Line (1-2 lines)'), ('calc_space', 'Calculation Space'), ('table_cell', 'Table Cell'), ('canvas', 'Drawing Canvas')], default='text_line', max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=600)),
                ('height', models.IntegerField(default=80)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_spaces', to='core.question')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswerSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True)),
                ('canvas_data', models.TextField(blank=True)),
                ('rasterized_image', models.TextField(blank=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answerspace')),
                ('student_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_responses', to='core.studentanswer')),
            ],
            options={
                'unique_together': {('student_answer', 'answer_space')},
            },
        ),
        migrations.CreateModel(
            name='QuestionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('page_image', models.TextField()),
                ('has_green_line', models.BooleanField(default=False)),
                ('has_red_line', models.BooleanField(default=False)),
                ('blue_rect_x', models.IntegerField(blank=True, null=True)),
                ('blue_rect_y', models.IntegerField(blank=True, null=True)),
                ('blue_rect_width', models.IntegerField(blank=True, null=True)),
                ('blue_rect_height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.question')),
            ],
            options={
                'ordering': ['question', 'page_number'],
                'unique_together': {('question', 'page_number')},
            },
        ),
    ]
