# Generated by Django 4.2.1 on 2026-02-24 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_studentanswer_time_spent_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, related_name='shared_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
