# Generated by Django 4.2.1 on 2026-02-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_test_assigned_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedpdf',
            name='question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
