# Generated by Django 4.2.1 on 2026-02-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_resource_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_level',
            field=models.CharField(blank=True, default='', help_text='Curriculum level grouping, e.g. IGCSE, DP, A Level', max_length=50),
        ),
    ]
