"""
Django settings for assessment_v3 project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

try:
    import dj_database_url
    _HAS_DJ_DATABASE_URL = True
except ImportError:
    _HAS_DJ_DATABASE_URL = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-h=9a(!o)u!le4os-2_vz1b)lwc-@idf7vq(%kn4773#u3v(n7*')

# ── LMStudio configuration ────────────────────────────────────────
# Change these if your LMStudio server moves to a different IP/port.
LMSTUDIO_URL = 'http://192.168.1.105:1234/v1/chat/completions'
LMSTUDIO_MODEL = 'openai/gpt-oss-20b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
<<<<<<< HEAD
    ".pythonanywhere.com",   # PythonAnywhere
    ".ngrok-free.app",       # ngrok tunnels
    ".railway.app",          # Railway
    ".run.app",              # Google Cloud Run
]

# Allow any extra host specified via environment variable (e.g. custom domain)
if os.environ.get('ALLOWED_HOST'):
    ALLOWED_HOSTS.append(os.environ['ALLOWED_HOST'])
=======
    ".ngrok-free.app",   # allows ALL ngrok subdomains
    ".railway.app",      # Railway domains
    ".run.app",          # Google Cloud Run domains
]

# Add Cloud Run domain dynamically
if os.environ.get('CLOUD_RUN_SERVICE_NAME'):
    ALLOWED_HOSTS.append(f"{os.environ.get('CLOUD_RUN_SERVICE_NAME')}.run.app")
>>>>>>> 00fd1b539d0cd3c647de646bd917a039c05b2cda

CSRF_TRUSTED_ORIGINS = [
    "https://*.pythonanywhere.com",
    "https://*.ngrok-free.app",
    "https://*.railway.app",
<<<<<<< HEAD
    "https://*.run.app",
=======
    "https://*.run.app",  # Google Cloud Run
>>>>>>> 00fd1b539d0cd3c647de646bd917a039c05b2cda
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'assessment_v3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.student_results_available',
            ],
        },
    },
]

WSGI_APPLICATION = 'assessment_v3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

<<<<<<< HEAD
# Use PostgreSQL if DATABASE_URL env var is set, otherwise SQLite
if os.environ.get('DATABASE_URL') and _HAS_DJ_DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
=======
# Use PostgreSQL in production (Cloud Run/Railway), SQLite in development
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ.get('DATABASE_URL'),
>>>>>>> 00fd1b539d0cd3c647de646bd917a039c05b2cda
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Static files configuration
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Whitenoise: serve compressed, cached static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Google OAuth Configuration
GOOGLE_OAUTH_CLIENT_ID = '833291367883-dm8ebjtstku36gm673tj3cpk84prjr97.apps.googleusercontent.com'
GOOGLE_OAUTH_CLIENT_SECRET = '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'

# Dynamic redirect URI - will be set at runtime based on request domain
# This is overridden in google_oauth.py to use the actual request domain
GOOGLE_OAUTH_REDIRECT_URI = 'http://127.0.0.1:8000/accounts/google/callback/'
